### ISSUE TITLE
Support for setting start_time

### ISSUE THREAD

**Issue by iilyak** [sile/passage#2]
We are considering using passage for CouchDB (see PR https://github.com/apache/couchdb/pull/2286). However we need to delay start_span call until we have information we need. However if we would do it we will get incorrect value for start_time. Would it be possible to add support for passing start_time value to start_span?

**Comment by iilyak** [comment]
Never mind. There is [support already](https://github.com/sile/passage/blob/master/src/passage.erl#L127)

**Comment by sile** [comment]
😄
