### ISSUE TITLE
OpenTracing becoming OpenTelemetry

### ISSUE THREAD

**Issue by tsloughter** [sile/passage#3]
Hey, @sile, I wanted to reach out about collaborating because OpenTracing is being sunset and merged with the OpenCensus project to become OpenTelemetry https://opentelemetry.io/

Certainly no reason for users to ditch OpenTracing yet, but future development is happening on OpenTelemetry, both on the spec and for services that accept traces. OpenTelemetry has a collector (https://github.com/open-telemetry/opentelemetry-collector/) with support for many various exporters by default as well as contributed exporters for external vendors https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter

I've been trying to contact all the various people who have implemented OpenTracing for Erlang and Elixir, there are many :). Some, like the maintainers of Spandex, are helping with OpenTelemetry and plan to deprecate their project, others not so much because its something used at their work and just not interested right now in dealing with anything else -- perfectly understandable.

I just wanted to reach out to mention this and that we have an OpenTelemetry SIG but run it through the Erlang Ecosystem Foundation as part of the Observability WG https://github.com/erlef/eef-observability-wg/

**Comment by sile** [comment]
Hi, @tsloughter, thank you for letting me know that.

>  its something used at their work and just not interested right now in dealing with anything else

This is similar to my case and, currently, I have no plan to develop `passage` further.  So, I'd like to leave this library as it is.
However, if I have a chance to implement tracing features in a new project, I'll consider contributing to or using OpenTelemetry libraries.

**Comment by tsloughter** [comment]
Understood, thanks. I'll close this issue.
